# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xci
# IP: The module: 'hdmi_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.gen/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.gen/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.gen/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xci
# IP: The module: 'hdmi_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.gen/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.gen/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ariane/Documentos/faculdade/semestre_5/sistemas_digitais/praticas/HDMI/HDMI.gen/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
